name: .NET CI/CD for FireSchema.CS.Runtime

on:
  push:
    branches: [ "main" ] # Trigger on push to main
    tags:
      - 'v*' # Also trigger on version tags like v0.1.0, v1.2.3
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.csproj'
      - '*.sln'
      - '.github/workflows/dotnet-ci-cd.yml'
  pull_request:
    branches: [ "main" ] # Trigger on PRs targeting main
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.csproj'
      - '*.sln'
      - '.github/workflows/dotnet-ci-cd.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  build-pack-publish: # Simplified job name
    runs-on: ubuntu-latest # Use Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Match project target framework if possible, or use LTS

    - name: Restore dependencies
      run: dotnet restore # Restore solution/directory

    - name: Build
      run: dotnet build --configuration Release # Build solution/directory, no --no-restore

    # Pack step without --no-build or --no-restore
    - name: Pack NuGet package
      if: startsWith(github.ref, 'refs/tags/v') # Only pack on tag pushes
      run: dotnet pack FireSchema.CS.Runtime.csproj --configuration Release -o ./nuget-package

    - name: Publish NuGet package
      if: startsWith(github.ref, 'refs/tags/v') # Only publish on tag pushes
      run: dotnet nuget push ./nuget-package/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    # Test step removed temporarily to isolate packing issue