name: .NET CI/CD for FireSchema.CS.Runtime

on:
  push:
    branches: [ "main" ] # Trigger on push to main
    tags:
      - 'v*' # Also trigger on version tags like v0.1.0, v1.2.3
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.csproj'
      - '*.sln'
      - '.github/workflows/dotnet-ci-cd.yml'
  pull_request:
    branches: [ "main" ] # Trigger on PRs targeting main
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.csproj'
      - '*.sln'
      - '.github/workflows/dotnet-ci-cd.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Match project target framework if possible, or use LTS

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        # No authentication needed for emulator
        install_components: 'beta, cloud-firestore-emulator' # Install components via the action

    - name: Start Firestore Emulator
      # We need the emulator for integration tests
      run: |
        echo "Starting Firestore emulator..."
        gcloud beta emulators firestore start --host-port="localhost:8080" &
        sleep 5 # Give emulator time to start

    - name: Test
      # Set environment variable for tests to find the emulator
      env:
        FIRESTORE_EMULATOR_HOST: "localhost:8080"
      run: dotnet test --configuration Release --verbosity normal

    - name: Pack NuGet package
      if: startsWith(github.ref, 'refs/tags/v') # Only pack on tag pushes
      run: |
        dotnet restore FireSchema.CS.Runtime.csproj
        dotnet pack FireSchema.CS.Runtime.csproj --configuration Release --no-build -o ./nuget-package

    - name: Publish NuGet package
      if: startsWith(github.ref, 'refs/tags/v') # Only publish on tag pushes
      run: dotnet nuget push ./nuget-package/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate